### ISSUE TITLE
我想问下那个css是怎么被插入到index.html

### ISSUE THREAD

**Issue by dzjwan521** [KieSun/webpack-demo#2]
我想问下那个css是怎么被插入到index.html
能加一个关于这个插件的步骤吗

**Comment by KieSun** [comment]
我没有在 index.html 中引入 CSS 文件，都是在 JS 中引入的

**Comment by dzjwan521** [comment]
没表达清楚,我在run dev后  看html里面被插入了css,我没清楚是怎么么办到的

**Comment by KieSun** [comment]
你有看上面的小节么，有介绍 html-webpack-plugin 插件，这个插件会帮你自动引入文件
